
BPAS_ADD_SANITY_TEST(FFT_test1 FFT_test_exe FILES 
	${CMAKE_CURRENT_SOURCE_DIR}/FFT/src/fft.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/FFT/src/oldfft.cpp
	ARGUMENTS 0 16384
)

BPAS_ADD_SANITY_TEST(FFT_test2 FFT_test_exe FILES 
	${CMAKE_CURRENT_SOURCE_DIR}/FFT/src/fft.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/FFT/src/oldfft.cpp
	ARGUMENTS 1 16384
)